[Layouts]
; https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/default-input-locales-for-windows-language-packs?view=windows-11
; English (United States)
Layout1=00000409
; 00000804 = Chinese (Simplified, PRC)
Layout2=00000804

[Hotkey]
SwitchKey=CapsLock

[Shortcuts]
; Shortcut keys configured in Windows Advanced Keyboard Settings
; Shortcut key for switching to Layout1 (number)
Shortcut1=0
; Shortcut key for switching to Layout2 (number)
Shortcut2=1
