[Layouts]
; https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/default-input-locales-for-windows-language-packs?view=windows-11
; English (United States)
Layout1=00000409
; 00000804 = Chinese (Simplified, PRC)
Layout2=00000804

[Hotkey]
SwapEscCapsLock=1
NotifyOnSwitch=1

[Shortcuts]
; Shortcut keys configured in Windows Advanced Keyboard Settings
Shortcut1=1
Shortcut2=2
